[build]
  command = "npm run build"
  publish = "frontend/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"

[context.production]
  environment = { NODE_VERSION = "18", NPM_VERSION = "9" }

[context.deploy-preview]
  environment = { NODE_VERSION = "18", NPM_VERSION = "9" }
